#kafka配置
spring:
    kafka:
      #kafka服务地址
      bootstrap-servers: localhost:9092
      #生产者配置
      producer:
        # 重试次数
        retries: 3
        # 批量发送的消息数量
        batch-size: 16384
        # 32MB的批处理缓冲区
        buffer-memory: 33554432
        
        #消费者配置
      consumer:
        # 默认消费者组
        group-id: etl
        # 最早未被消费的offset
        auto-offset-reset: earliest
        # 批量一次最大拉取数据量
        max-poll-records: 1
        # 自动提交
        auto-commit-interval: 1000
        enable-auto-commit: true
      # 配置监听器容器
      listener: 
        concurrency: 2
server:
    port: 8089