server: 
    port: 8765

spring: 
    # 第一个数据源
    datasource: 
        one: 
            url: jdbc:mysql://localhost:3306/test-jndi-db?useUnicode=true&amp;characterEncoding=UTF-8
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
        two: 
            url: jdbc:mysql://localhost:3306/world?useUnicode=true&amp;characterEncoding=UTF-8
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
            
    